pipeline {
    agent {
        dockerfile {
            dir 'pipeline-Scenarios'
            filename 'Dockerfile.sdk'
        }
    }
    environment {
    DOTNET_CLI_HOME = "/tmp/DOTNET_CLI_HOME"
}
    stages {
        stage('Verify') {
            steps {
                sh '''
                  dotnet --list-sdks
                  dotnet --list-runtimes
                '''
                sh 'printenv'
                sh 'ls -l "$WORKSPACE"'
            }
        }
        stage('Build') {
            steps {
                sh 'dotnet build "$WORKSPACE/pipeline-Scenarios/src/web-api/web-api.csproj"'
            }
        }
        stage('API Unit Test') {
            steps {
              dir("$WORKSPACE/pipeline-Scenarios/src") {
                sh '''
                    dotnet test web-api-tests/web-api-tests.csproj
                '''
              }
            }
        }
        stage('Smoke Test') {
            steps {
              sh 'dotnet "$WORKSPACE/pipeline-Scenarios/src/web-api/bin/Debug/net6.0/web-api.dll"'
            }
        }
    }
}
